name: publish-docker-image

on:
  push:
    branches:
      - main

jobs:
  publish-docker-image-on-github-cr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_NihadVeliyev }}  # Or GHCR_PASSWORD if renamed
          logout: true

      - name: Build 🔧 and Push 📦 the Docker image of my personal portfolio on GitHub Container Registry
        run: |
          docker build -t ghcr.io/nihadveliyev/nihadveliyev.github.io:latest .
          docker push ghcr.io/nihadveliyev/nihadveliyev.github.io:latest

  publish-docker-image-on-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: "nihadveliyev"  # Update to your DockerHub username
          password: ${{ secrets.DOCKERHUB }}

      - name: Build 🔧 and Push 📦 the Docker image of my personal portfolio on DockerHub
        run: |
          docker build -t nihadveliyev/nihadveliyev.github.io:latest .
          docker push nihadveliyev/nihadveliyev.github.io:latest
